# 카메라 파라미터 설정
camera:
  width: 640          # 이미지 너비 (픽셀)
  height: 480         # 이미지 높이 (픽셀)
  fov: 90.0           # 시야각 (Field of View) - 각도 단위
  x: 0.61              # 차량 좌표계 기준 X 위치 (미터)
  y: 0.0              # 차량 좌표계 기준 Y 위치 (미터)
  z: 1.15              # 차량 좌표계 기준 Z 위치 (미터)
  roll: 0.0           # Roll 각도 (라디안) - X축 회전
  pitch: 0.0          # Pitch 각도 (라디안) - Y축 회전
  yaw: 0.0            # Yaw 각도 (라디안) - Z축 회전

# 라이다 파라미터 설정
lidar:
  x: 0.36              # 차량 좌표계 기준 X 위치 (미터)
  y: 0.0              # 차량 좌표계 기준 Y 위치 (미터)
  z: 0.65             # 차량 좌표계 기준 Z 위치 (미터)
  roll: 0.0           # Roll 각도 (라디안) - X축 회전
  pitch: 0.0          # Pitch 각도 (라디안) - Y축 회전
  yaw: 0.0            # Yaw 각도 (라디안) - Z축 회전