# 캘리브레이션 파라미터 - 저장 시간: 2025-04-07 22:28:09
# 카메라 파라미터 설정
camera:
  width: 640          # 이미지 너비 (픽셀)
  height: 480         # 이미지 높이 (픽셀)
  fov: 90           # 시야각 (Field of View) - 각도 단위
  x: 1.9              # 차량 좌표계 기준 X 위치 (미터)
  y: 0.23              # 차량 좌표계 기준 Y 위치 (미터)
  z: 1.42              # 차량 좌표계 기준 Z 위치 (미터)
  roll: 0           # Roll 각도 (라디안) - X축 회전
  pitch: -0.0314159          # Pitch 각도 (라디안) - Y축 회전
  yaw: 0.00383972            # Yaw 각도 (라디안) - Z축 회전

# 라이다 파라미터 설정
lidar:
  x: 1.37              # 차량 좌표계 기준 X 위치 (미터)
  y: -0.01              # 차량 좌표계 기준 Y 위치 (미터)
  z: 0.95             # 차량 좌표계 기준 Z 위치 (미터)
  roll: 0.00139626           # Roll 각도 (라디안) - X축 회전
  pitch: -0.000523599          # Pitch 각도 (라디안) - Y축 회전
  yaw: 0.00645772           # Yaw 각도 (라디안) - Z축 회전
